'use strict';

module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define('User', {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoGenerated: true, 
    } ,
    firstName: {
      type:DataTypes.STRING,
      allowNull: false,   
    },
    lastName: {
      type: DataTypes.STRING,
      allowNull: false,   
    },
    emailAddress: {
      type: DataTypes.STRING,
      allowNull: false,   
    },
    password: {
      type:DataTypes.STRING,
      allowNull: false,   
    },
  }, { sequelize });
  User.associate = function(models) {
    // define associations
    User.hasMany(models.User, {
      foreignKey: {
        fieldName: 'directorUserId',
        allowNull: false,
      },
    });
  };
  return User;
};